QLBB/Controllers/DanhGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLBB.Models;
using QLBB.Models.ViewModels;

namespace QLBB.Controllers
{
    public class DanhGiaController : Controller
    {
        private QLBanhEntities db = new QLBanhEntities();
        // GET: DanhGia
        public ActionResult Index(int ?F)
        {
            List<Comment> cmt = db.Comments.OrderByDescending(s => s.Createon).Where(s => s.MaMenu == F /*&& s.Createon.Value.Month == DateTime.Now.Month*/).ToList();
            return View(cmt);
        }
        [HttpGet]
        public ActionResult PostComment(int? F)
        {
            return View();
        }
        [HttpPost]
        public ActionResult PostComment(object sender, string cmttext, int? F,EventArgs e)
        {
            KhachHang kh = (KhachHang)Session["Taikhoan"];
            if (Session["Taikhoan"] == null || Session["Taikhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
            //F = Convert.ToInt32(Request.QueryString["imenu"]);
            Comment c = new Comment();
           c.DanhGia = cmttext;
            var querystringFromUrlReferrer = HttpUtility.ParseQueryString(HttpContext.Request.UrlReferrer.Query);
             c.MaMenu = int.Parse(querystringFromUrlReferrer["F"]);
            c.MaKH = kh.MaKH;
                c.Createon = DateTime.Now;
                db.Comments.Add(c);
                db.SaveChanges();
            
            return RedirectToAction("Index");
        }
        public ActionResult XemDanhGia(int? id)
        {
            List<Comment> cmt = db.Comments.OrderByDescending(s => s.Createon).Where(s => s.MaMenu == id).ToList();
            return View(cmt);
        }
    }
}

QLBB/Controllers/NhaHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLBB.Models;
using QLBB.Models.ViewModels;

namespace QLBB.Controllers
{
    public class NhaHangController : Controller
    {
        private QLBanhEntities db = new QLBanhEntities();
        // GET: NhaHang
        public ActionResult Index(Menu menuList)
        {
            Session["Menu"] = menuList;
            List<Menu> dsp = db.Menus.Where(s=>s.NoiBat==true).ToList();
            Session["Menu"] = dsp;
            return View(dsp);
        }
        public ActionResult Details(int? id,int? iMaMenu,Menu menuList)
        {
            //var model = db.SanPhams.Where(s => s.MaMenu == id && s.Deleted == false).Select(i => new bigmodel
            //{
            //    TenMenu = i.Menu.TenMenu,
            //    HinhSP=i.HinhSP,
            //    TenSP=i.TenSP,
            //    GhiChu=i.GhiChu,
            //    DonGia=i.DonGia,
            //}).ToList();
                 
            //foreach (var item in model)
            //{
            //     var p = db.SanPhams.Where(s => s.MaMenu == id && s.Deleted == false).ToList();
            //}
            List<SanPham> model = db.SanPhams.Where(s => s.MaMenu == id && s.Deleted == false).ToList();
            //List<Giohang> gh = Index();
            //List<bigmodel> lstGiohang = Session["bigmodel"] as List<bigmodel>;
            return View(model);
        }
        public ActionResult List()
        {
            List<Menu> dsp = db.Menus.ToList();
            return View(dsp);
        }
        public ActionResult SearchByName(string name)
        {
            //List<SanPham> p = db.SanPhams.Where(s => s.TenSP.Contains(name)).ToList();
            List<Menu> p = db.Menus.Where(s => s.TenMenu.Contains(name)).ToList();

            ViewBag.keyword = name;

            return View(p);
        }
        public ActionResult XemCTHD(int? id)
        {

            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

                return null;
            KhachHang kh = Session["TaiKhoan"] as KhachHang;
            var ls = from s in db.HoaDons.OrderByDescending(s=>s.NgayDat)
                     where s.MaKH == kh.MaKH && s.TinhTrangGiaoHang==false
                     select s;

            return PartialView(ls.ToList());
        }

        public ActionResult LSDH(int? id)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

                return null;
            KhachHang kh = Session["TaiKhoan"] as KhachHang;
            var ls = from s in db.HoaDons.OrderByDescending(s => s.NgayDat)
                     where s.MaKH == kh.MaKH && s.TinhTrangGiaoHang == true
                     select s;

            return PartialView(ls.ToList());

        }
        public ActionResult XemChiTiet(int? id)
        {
            CTHD CT = db.CTHDs.FirstOrDefault(s => s.MaHD == id);
            return View(CT);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }

     
    }
}

QLBB/Views/NhaHang/Details.cshtml
<style>
    body {
        margin-top: 0 auto;
        font-family: "Times New Roman", Times, serif;
    }

    .lop-sp {
        float: left;
        width: 28%;
        text-align: center;
        padding: 10px 5px;
        margin: 10px auto;
        font-weight: bold;
        word-wrap: break-word;
        margin-left: 3%;
        margin-right: 2%;
        /*border: 2px solid transparent;
        border-color: gray;*/
        font-size: 100%;
        background-color: white;
        border-radius: 8px;
        background-color: #fbf3f3;
        height: 165px;
    }

        .lop-sp:hover {
            transform: scale(1.07);
        }

        .lop-sp .tua-sp {
            word-wrap: break-word;
            font-size: 100%;
            color: black;
            text-align: left;
            margin-bottom: 10px;
            float: right;
            width: 58%;
        }

    .tua-sp :link {
        color: black;
    }

    .lop-sp .lop-hinh {
        text-align: center;
        padding: 0;
        margin-bottom: 2px;
        float: left;
        width: 40%;
        margin-top: 5px;
    }
</style>
@using QLBB.Models;

@model IEnumerable<QLBB.Models.SanPham>
@*@model List<QLBB.Models.ViewModels.bigmodel>*@
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Menudoc.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<h2>&nbsp;</h2>
@if (TempData["AlertMessage"] != null)
{
    <div id="AlertBox" class="alert @TempData["AlertType"] hide" role="alert">
        @TempData["AlertMessage"]
    </div>
}
@*<section id="home" class="w3l-banner py-5">
    <div class="container py-lg-5 py-md-4">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="~/NhaHang/Detail"><i class="fa fa-pencil-square-o">Đặt đơn</i>@ViewBag.ThongKeDon</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/DanhGia/XemDanhGia"><i class="fa fa-comments" aria-hidden="true"> Bình luận</i></a>
            </li>
        </ul>
      @Html.ActionLink("1","XemDanhGia","DanhGia",new { id = ViewBag.MaMenu })
            @Html.ActionLink("XemDanhGia", "DanhGia")*@
            @foreach (var item in Model)
            {

                <div class="lop-sp">

                    <div class="lop-hinh">
                        @*<img width="100%" src="/@item.HinhSP" alt="HinhSP" />*@
                        @*<img src='@Url.Content("~/Content/Images/MyLinkImage.png")' />*@
                        <a>
                            <img style="width:130px;height:130px;border-radius:10px" src="/@item.HinhSP" alt="HinhSP" />
                        </a>
                    </div>
                    <p class="tua-sp" style="font-size:90%">

                        <a>
                            @Html.DisplayFor(modelItem => item.TenSP)
                        </a>
                    </p>
                    <p class="tua-sp" style="font-size:80%;color:dimgray">
                        @Html.DisplayFor(modelItem => item.GhiChu)

                    </p>
                    @*<p class="tua-sp" style="font-size:90%;color:dimgray">
                    &nbsp;
                    </p>*@
                    <p class="tua-sp" style="font-size:90%;">
                        <a style="float:left;width:70%">
                            @String.Format("{0:#,0}", item.DonGia)
                        </a>
                        <a class="btn btn-success" @*onclick="myFunction()"*@ href="@Url.Action("ThemGioHang", "GioHang", new { @iMaSP=item.MaSP, @iMaMenu=item.MaMenu,@strURL=Request.Url.ToString()})" style="float:right;width:25%">
                            @*<span class="glyphicon glyphicon-shopping-cart"></span>*@ <i class="fa fa-plus" aria-hidden="true"></i>
                        </a>
                    </p>

                </div>
            }
</div>
</section>
@if (TempData["Msg"] != null)
{
    <script>
        confirm('@Html.Raw(TempData["Msg"])')
    </script>

}

QLBB/Views/NhaHang/Index.cshtml
    <style>
        .lop-sp {
            float: left;
            width: 27%;
            text-align: center;
            padding: 10px 5px;
            margin: 0 auto;
            font-weight: bold;
            word-wrap: break-word;
            /*margin-top:17%;*/
            margin-left: 4%;
            margin-right: 2%;
            font-size: 100%;
        }
          .lop-sp:hover {
                transform: scale(1.07);
            }

            .lop-sp .tua-sp {
                word-wrap: break-word;
                font-size: 100%;
                color: black;
                text-align: left;
                margin-bottom: 10px;
                margin-left:10px;
            }

        .tua-sp:link {
            color: black;
        }

        a:link {
            color: black;
        }

        .lop-sp .lop-hinh {
            text-align: center;
            padding: 0;
            margin-bottom: 15px;
        }
      
       
    </style>
    @model IEnumerable<QLBB.Models.Menu>
    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/Home.cshtml";

    }

<h2>&nbsp;</h2>
<h4 style="color:#404F5E;text-align:right">
    @Html.ActionLink("Xem thêm >>", "List", "NhaHang")
</h4>
<h2>&nbsp;</h2>
@foreach (var item in Model)
{
    <div class="lop-sp">
        <div class="lop-hinh ">
            <a href='@Url.Action("Details", "NhaHang", new { id = item.MaMenu })'>
                <img style="width:275px;height:170px;border-radius:15px" src="/@item.Logo" alt="HinhSP" />
            </a>
        </div>

        <p class="tua-sp" style="font-size:120%;color:black">
            <a style="color:black" href='@Url.Action("Details", "NhaHang", new { id = item.MaMenu })'>
                @Html.DisplayFor(modelItem => item.TenMenu)
            </a>- @Html.DisplayFor(modelItem => item.DiaChi)
        </p>
        <p class="tua-sp" style="font-size:110%;color:dimgray">
            @Html.DisplayFor(modelItem => item.PhanLoaiMN.TenPhanLoaiMN)
            -<a href="~/DanhGia/XemDanhGia?id=@item.MaMenu"> Đánh giá</a>
            @*-@Html.ActionLink(new { controller = "DanhGia", action = "XemDanhGia",id = item.MaMenu})*@
        </p>
       
    </div>
}

QLBB/Views/NhaHang/LSDH.cshtml
@model IEnumerable<QLBB.Models.HoaDon>
@{
        ViewBag.Title = "LSDH";
        Layout = "~/Views/Shared/DonHang.cshtml";
    }
&nbsp;
<h2>Lịch sử đơn hàng</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DaThanhToan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TinhTrangGiaoHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayDat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayGiao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KhachHang.HoTen)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @Html.DisplayFor(modelItem => item.ThanhToan.TinhTrang)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.TinhTrangGiaoHang)*@
                @Html.DisplayFor(modelItem => item.GiaoHang.GiaoHangTT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "SuaHD", new { id = item.MaHD })*@
                @Html.ActionLink("Details", "XemChiTiet", new { id = item.MaHD })
            </td>

            @*<td>
                @Html.ActionLink("Đánh Giá", "PostComment",new { controller = "DanhGia",@imenu=item.MaMenu })
            </td>*@
            <td>
                @Html.ActionLink("Đánh Giá", "Index", new { controller = "DanhGia", @F=item.MaMenu })
            </td>
        </tr>
    }

</table>

QLBB/Views/NhaHang/List.cshtml
<style>
    .lop-sp {
        float: left;
        width: 27%;
        text-align: center;
        padding: 10px 5px;
        margin: 0 auto;
        font-weight: bold;
        word-wrap: break-word;
        /*margin-top:17%;*/
        margin-left: 4%;
        margin-right: 2%;
        font-size: 100%;
    }

        .lop-sp:hover {
            transform: scale(1.07);
        }

        .lop-sp .tua-sp {
            word-wrap: break-word;
            font-size: 100%;
            color: black;
            text-align: left;
            margin-bottom: 10px;
            margin-left: 10px;
        }

    .tua-sp:link {
        color: black;
    }

    a:link {
        color: black;
    }

    .lop-sp .lop-hinh {
        text-align: center;
        padding: 0;
        margin-bottom: 15px;
    }
</style>
@model IEnumerable<QLBB.Models.Menu>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Menudoc.cshtml";

}

<h2>&nbsp;</h2>
@foreach (var item in Model)
{
    <div class="lop-sp">
        <div class="lop-hinh ">
            <a href='@Url.Action("Details", "NhaHang", new { id = item.MaMenu })'>
                <img style="width:285px;height:180px;border-radius:15px" src="/@item.Logo" alt="HinhSP" />
            </a>
        </div>

        <p class="tua-sp" style="font-size:120%;color:black">
            <a style="color:black" href='@Url.Action("Details", "NhaHang", new { id = item.MaMenu })'>
                @Html.DisplayFor(modelItem => item.TenMenu)
            </a>- @Html.DisplayFor(modelItem => item.DiaChi)
        </p>
        <p class="tua-sp" style="font-size:110%;color:dimgray">
            @Html.DisplayFor(modelItem => item.PhanLoaiMN.TenPhanLoaiMN)
        </p>

    </div>
}

QLBB/Views/NhaHang/SearchByName.cshtml
<style>
    .lop-sp {
        float: left;
        width: 27%;
        text-align: center;
        padding: 10px 5px;
        margin: 0 auto;
        font-weight: bold;
        word-wrap: break-word;
        /*margin-top:17%;*/
        margin-left: 4%;
        margin-right: 2%;
        font-size: 100%;
    }

        .lop-sp:hover {
            transform: scale(1.07);
        }

        .lop-sp .tua-sp {
            word-wrap: break-word;
            font-size: 100%;
            color: black;
            text-align: left;
            margin-bottom: 10px;
            margin-left: 10px;
        }

    .tua-sp:link {
        color: black;
    }

    a:link {
        color: black;
    }

    .lop-sp .lop-hinh {
        text-align: center;
        padding: 0;
        margin-bottom: 15px;
    }
</style>
@model IEnumerable<QLBB.Models.Menu>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Menudoc.cshtml";

}
<h4>Kết quả tìm kiếm:</h4>
@foreach (var item in Model)
{
    <div class="lop-sp">
        <div class="lop-hinh ">
            <a href='@Url.Action("Details", "NhaHang", new { id = item.MaMenu })'>
                <img style="width:275px;height:170px;border-radius:15px" src="/@item.Logo" alt="HinhSP" />
            </a>
        </div>

        <p class="tua-sp" style="font-size:120%;color:black">
            <a style="color:black" href='@Url.Action("Details", "NhaHang", new { id = item.MaMenu })'>
                @Html.DisplayFor(modelItem => item.TenMenu)
            </a>- @Html.DisplayFor(modelItem => item.DiaChi)
        </p>
        <p class="tua-sp" style="font-size:120%;color:dimgray">
            @Html.DisplayFor(modelItem => item.PhanLoaiMN.TenPhanLoaiMN)
        </p>

    </div>
}

QLBB/Views/NhaHang/XemCTHD.cshtml
@model IEnumerable<QLBB.Models.HoaDon>
@{
    ViewBag.Title = "XemCTHD";
    Layout = "~/Views/Shared/DonHang.cshtml";
}
&nbsp;
<h2>XemCTHD</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DaThanhToan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TinhTrangGiaoHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayDat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayGiao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KhachHang.HoTen)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @Html.DisplayFor(modelItem => item.ThanhToan.TinhTrang)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.TinhTrangGiaoHang)*@
                @Html.DisplayFor(modelItem => item.GiaoHang.GiaoHangTT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "SuaHD", new { id = item.MaHD })*@
                @Html.ActionLink("Details", "XemChiTiet", new { id = item.MaHD })
            </td>
        </tr>
    }

</table>

QLBB/Views/NhaHang/XemChiTiet.cshtml
@model QLBB.Models.CTHD

@{
    ViewBag.Title = "XemChiTiet";
    Layout = "~/Views/Shared/Menudoc.cshtml";
}

<h2>XemChiTiet</h2>

<div>
    <h4>CTHD</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoaDon.MaHD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoaDon.MaHD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Menu.TenMenu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.TenMenu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SanPham.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPham.TenSP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>