QLBB/Models/CTHD.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
        public Nullable<int> MaMenu { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}

QLBB/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public string HinhSP { get; set; }
        public int MaMenu { get; set; }
        public bool Deleted { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
    }
}

QLBB/Models/ViewModels/SanPhamViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QLBB.Models.ViewModels
{
    public class SanPhamViewModels
    {
      
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> MaPhanLoai { get; set; }
        public string HinhSP { get; set; }
        public bool Deleted { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaMenu { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CTHD> CTHDs { get; set; }
        public IEnumerable<Menu> ListMenu { get; set; }
        public IEnumerable<PhanLoai> ListPhanLoai { get; set; }
    }
}

QLBB/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLBB.Models;
using QLBB.Models.ViewModels;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

using PagedList;
using PagedList.Mvc;
namespace QLBB.Areas.Admin.Controllers
{
    public class SanPhamController : BaseController
    {
        // GET: Admin/SanPham
        private QLBanhEntities db = new QLBanhEntities();
        // GET: Phim
        public ActionResult Home()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

                return null;
            DoiTac dt = Session["TaiKhoan"] as DoiTac;
            var listsp = from s in db.SanPhams
                         where s.MaMenu == dt.MaMenu && !s.Deleted
                         select s;

            return PartialView(listsp.ToList());
        }
        public ActionResult Index()
        {

            /*List<Phim> dsp = db.Phims.ToList();*/
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

                return null;
            DoiTac dt = Session["TaiKhoan"] as DoiTac;
            var listsp = from s in db.SanPhams
                         where s.MaMenu == dt.MaMenu && !s.Deleted
                         select s;
            
            return PartialView(listsp.ToList());
        
            

        }
        public ActionResult Create()
        {
            //Lấy ra ds loại sp
            SanPhamViewModels pModel = new SanPhamViewModels();
            pModel.ListPhanLoai = db.PhanLoais.ToList();
            pModel.ListMenu = db.Menus.ToList();
            return View(pModel);
        }
        [HttpPost]
        public ActionResult Create(SanPham p, HttpPostedFileBase fileUpload)
        {
            //lấy tên file
            var fileName = Path.GetFileName(fileUpload.FileName);
            //Tạo đường dẫn lưu file
            var filePath = Path.Combine(Server.MapPath("~/Content/image"), fileName);
            //Lưu ảnh xuống thư mục img
            fileUpload.SaveAs(filePath);
            //kt có ảnh chưa
            if (!System.IO.File.Exists(filePath))
                fileUpload.SaveAs(filePath);


            SanPham SanPhamM = new SanPham();
            SanPhamM.TenSP = p.TenSP;
            SanPhamM.DonGia = p.DonGia;
            SanPhamM.MaPhanLoai = p.MaPhanLoai;
            SanPhamM.MaMenu = p.MaMenu;
            SanPhamM.GhiChu = p.GhiChu;
            SanPhamM.Deleted = false;
            //lưu đường dẫn vào database
            SanPhamM.HinhSP = "Content/image/" + fileName;
            //sanPhamMoi.HinhSP = sp.HinhSP;
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

                return null;
            DoiTac kh = Session["TaiKhoan"] as DoiTac;
            SanPhamM.MaMenu = kh.MaMenu;
            db.SanPhams.Add(SanPhamM);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)//truyền id
        {
            SanPham p = db.SanPhams.Where(s => s.MaSP == id).FirstOrDefault();
            ViewBag.MaPhanLoai = new SelectList
                (db.PhanLoais.ToList().
                OrderBy(s => s.TenPhanLoai), "MaPhanLoai", "TenPhanLoai");
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(SanPham sanpham, HttpPostedFileBase fileUpload)
        {
            //lấy tên file
            var fileName = Path.GetFileName(fileUpload.FileName);
            //Tạo đường dẫn lưu file
            var filePath = Path.Combine(Server.MapPath("~/Content/image"), fileName);
            //Lưu ảnh xuống thư mục img
            fileUpload.SaveAs(filePath);
            //kt có ảnh chưa
            if (!System.IO.File.Exists(filePath))
                fileUpload.SaveAs(filePath);


            SanPham p = db.SanPhams.Where(s => s.MaSP == sanpham.MaSP).FirstOrDefault();
            p.TenSP = sanpham.TenSP;
            p.DonGia = sanpham.DonGia;
            p.GhiChu = sanpham.GhiChu;
            p.MaPhanLoai = sanpham.MaPhanLoai;
            p.HinhSP = "Content/image/" + fileName; ;

            /* db.SanPhams.Add(sp);*///Thêm sp
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            SanPham p = db.SanPhams.FirstOrDefault(s => s.MaSP == id);
            return View(p);
        }
        public ActionResult Delete(int id)
        {
            SanPham p = db.SanPhams.Where(s => s.MaSP == id).FirstOrDefault();
            ViewBag.MaLoaiPhim = new SelectList
               (db.PhanLoais.ToList().
                OrderBy(s => s.TenPhanLoai), "MaPhanLoai", "TenPhanLoai");
            return View(p);
        }
        [HttpPost]
        public ActionResult Delete(SanPham sanpham, int id)
        {
            SanPham p = db.SanPhams.Single(s => s.MaSP == id);
            p.Deleted = true;
            //db.Entry(p).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("index");
        }
        public ActionResult SearchByName(string name)
        {
            List<SanPham> p = db.SanPhams.Where(s => s.TenSP.Contains(name)&& !s.Deleted).ToList();

            ViewBag.keyword = name;

            return View(p);
        }
        public ActionResult XemCTHD(int? id)
        {
            //int pageSize = 6;
            //int pageNum = (page ?? 1);
            //var cthd = (from l in db.HoaDons
            //            select l).OrderByDescending(s => s.MaHD);

            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

                return null;
            DoiTac kh = Session["TaiKhoan"] as DoiTac;
            var ls = from s in db.HoaDons.OrderByDescending(s => s.NgayDat)
                     where s.MaMenu == kh.MaMenu &&s.TinhTrangGiaoHang == false
                     select s;
            //ViewBag.MaHD = new SelectList
            // (db.CTHDs.ToList().
            //  OrderBy(s => s.MaMenu), "MaHD", "MaMenu");
            return PartialView(ls.ToList());
            //if (db.HoaDons.FirstOrDefault(s => s.DaThanhToan.Equals())
            //Console.Write("Chưa thanh toán");

            //return View(cthd.ToPagedList(pageNum, pageSize));
        }
        //public ActionResult DonHangMoi(int? id)
        //{

        //    if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

        //        return null;
        //    DoiTac kh = Session["TaiKhoan"] as DoiTac;
        //    var ls = from s in db.HoaDons
        //             where s.MaMenu == kh.MaMenu && s.TinhTrangGiaoHang == false
        //             select s;
        //    return PartialView(ls.ToList());
        //}

       
        public double TongSoLuongDon()
        {
            DoiTac dt = Session["TaiKhoan"] as DoiTac;
            var listsp = from s in db.HoaDons
                         where s.MaMenu == dt.MaMenu && s.TinhTrangGiaoHang==false
                         select s;
            double slDH = 0;
            foreach (var item in listsp)
            {
                slDH = db.CTHDs.Count();
            }
            return slDH;
        }
        public ActionResult DonHangPartial()
        {
            ViewBag.TongSoLuong = TongSoLuongDon();
            //ViewBag.Tongtien = TongTien();
            return PartialView();
        }
        public ActionResult CTHD(int id)
        {
            CTHD CT = db.CTHDs.FirstOrDefault(s => s.MaHD == id);
            return View(CT);
        }
        public ActionResult SuaHD(int id)
        {
            HoaDon p = db.HoaDons.Where(s => s.MaHD == id).FirstOrDefault();
            ViewBag.TinhTrangGiaoHang = new SelectList
                (db.GiaoHangs.ToList().OrderBy(s => s.TinhTrangGiaoHang), "TinhTrangGiaoHang", "GiaoHangTT");
            ViewBag.DaThanhToan = new SelectList
              (db.ThanhToans.ToList().OrderBy(s => s.DaThanhToan), "DaThanhToan", "TinhTrang");
            return View(p);
        }
        [HttpPost]
        public ActionResult SuaHD(HoaDon Hd)
        {
            HoaDon p = db.HoaDons.Where(s => s.MaHD == Hd.MaHD).FirstOrDefault();
            p.DaThanhToan = Hd.DaThanhToan;
            p.TinhTrangGiaoHang = Hd.TinhTrangGiaoHang;
            //p.NgayDat = Hd.NgayDat;
            //p.NgayGiao = Hd.NgayGiao;
            db.SaveChanges();
            return RedirectToAction("XemCTHD");
        }
        public ActionResult LSDH(int? id)
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")

                return null;
            DoiTac kh = Session["TaiKhoan"] as DoiTac;
            var ls = from s in db.HoaDons.OrderByDescending(s => s.NgayDat)
                     where s.MaMenu == kh.MaMenu && s.TinhTrangGiaoHang == true
                     select s;
    
            return PartialView(ls.ToList());

        }
        public ActionResult DanhGia(int? id)
        {
            DoiTac dt = Session["TaiKhoan"] as DoiTac;
            var listsp = from s in db.Comments.OrderByDescending(s=>s.Createon)
                         where s.MaMenu == dt.MaMenu
                         select s;
        
            return View(listsp.ToList());
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

QLBB/Controllers/DanhGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLBB.Models;
using QLBB.Models.ViewModels;

namespace QLBB.Controllers
{
    public class DanhGiaController : Controller
    {
        private QLBanhEntities db = new QLBanhEntities();
        // GET: DanhGia
        public ActionResult Index(int ?F)
        {
            List<Comment> cmt = db.Comments.OrderByDescending(s => s.Createon).Where(s => s.MaMenu == F /*&& s.Createon.Value.Month == DateTime.Now.Month*/).ToList();
            return View(cmt);
        }
        [HttpGet]
        public ActionResult PostComment(int? F)
        {
            return View();
        }
        [HttpPost]
        public ActionResult PostComment(object sender, string cmttext, int? F,EventArgs e)
        {
            KhachHang kh = (KhachHang)Session["Taikhoan"];
            if (Session["Taikhoan"] == null || Session["Taikhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
            //F = Convert.ToInt32(Request.QueryString["imenu"]);
            Comment c = new Comment();
           c.DanhGia = cmttext;
            var querystringFromUrlReferrer = HttpUtility.ParseQueryString(HttpContext.Request.UrlReferrer.Query);
             c.MaMenu = int.Parse(querystringFromUrlReferrer["F"]);
            c.MaKH = kh.MaKH;
                c.Createon = DateTime.Now;
                db.Comments.Add(c);
                db.SaveChanges();
            
            return RedirectToAction("Index");
        }
        public ActionResult XemDanhGia(int? id)
        {
            List<Comment> cmt = db.Comments.OrderByDescending(s => s.Createon).Where(s => s.MaMenu == id).ToList();
            return View(cmt);
        }
    }
}

QLBB/Areas/Admin/Views/SanPham/AdminHome.cshtml
<style>
    th {
        text-align: center;
    }

    td {
        text-align: center;
    }
</style>
@*@model IEnumerable<QLBanHangLuuNiem.Models.SanPham>*@
@using QLBB.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@if (Model.Any() && Model != null)
{
    <h2>Index</h2>

    <p>
        @*~/Admin/SanPham/XemCTHD*@
        @*@Html.ActionLink("Create New", "Create")*@
    </p>
    <table class="table">
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.TenSP)*@
                Tên Sản Phẩm
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.DonViTinh)*@
                Đơn giá
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.PhanLoai.TenPhanLoai)*@
                Phân loại
            </th>
            <th style="text-align:center">
                @*@Html.DisplayNameFor(model => model.HinhSP)*@
                Hình sản phẩm
            </th>

            <th>Chức năng</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TenSP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonGia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhanLoai.TenPhanLoai)
                </td>
                <td width="25%" style="text-align:center">
                    <img width="50%" src="/@item.HinhSP" alt="HinhSP" />
                </td>


                <td>
                    @*<a href="~/Admin/SanPham/Edit?id=@item.MaSP"></a>*@
                    <a href='@Url.Action("Edit", "SanPham", new { id=item.MaSP })'>
                        <i class="fas fa-edit" style="font-size:25px"></i>
                    </a>
                    <a href='@Url.Action("Delete", "SanPham", new { id=item.MaSP })'>
                        <i class="far fa-trash-alt" style="font-size:25px"></i>
                    </a>
                    <a href='@Url.Action("Details", "SanPham", new { id=item.MaSP })'>
                        <i class="fa fa-info" aria-hidden="true" style="font-size:30px"></i>
                    </a>
                    @*@Html.ActionLink("Edit", "Edit", new { id=item.MaSP }, new { @class = "fas fa-edit" })*@
                    @*@Html.ActionLink("Details", "Details", new { id=item.MaSP }, new { @class = "btn btn-success" })*@
                    @*@Html.ActionLink("Delete", "Delete", new { id=item.MaSP }, new { @class = "btn btn-success" })*@
                </td>
            </tr>
        }

    </table>
    <div style="text-align:center;clear:both">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

    </div>
}
else
{
    <h3>Hiện không có sản phẩm nào cả</h3>
}
@Scripts.Render("~/bundles/bootstrap")

QLBB/Areas/Admin/Views/SanPham/CTHD.cshtml
@model QLBB.Models.CTHD

@{
    ViewBag.Title = "CTHD";
    Layout = "~/Areas/Admin/Views/Shared/NewLayout.cshtml";
}

<h2>CTHD</h2>

<div>
    <h4>CTHD</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoaDon.MaHD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoaDon.MaHD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Menu.TenMenu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Menu.TenMenu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SanPham.TenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SanPham.TenSP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLBB/Areas/Admin/Views/SanPham/Create.cshtml
@model QLBB.Models.ViewModels.SanPhamViewModels
@using QLBB.Models;

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/NewLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "SanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaPhanLoai, "MaPhanLoai", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"> Phân loại</p>
            <div class="col-md-10">
                @*@Html.DropDownList("MaPhanLoai", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.MaPhanLoai,
               new SelectList(Model.ListPhanLoai, "MaPhanLoai", "TenPhanLoai"),
               null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPhanLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.HinhSP, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"> Hình sản phẩm</p>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.HinhSP, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="fileUpload" />
                @Html.ValidationMessageFor(model => model.HinhSP, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QLBB/Areas/Admin/Views/SanPham/DonHangPartial.cshtml
<a href="@Url.Action("XemCTHD","SanPham")" style="font-weight: bold; text-decoration:none;color:#999999;font:18px Nunito,san-serif">
    Đơn hàng <span class="badge badge-danger">@ViewBag.Tongsoluongdon</span>
</a>

QLBB/Areas/Admin/Views/SanPham/Edit.cshtml
@model QLBB.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "SanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.MaSP)
    @Html.HiddenFor(model=>model.Deleted)
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaPhanLoai, "MaPhanLoai", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2">Phân loại</p>
            <div class="col-md-10">
                @Html.DropDownList("MaPhanLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPhanLoai, "", new { @class = "text-danger" })
            </div>
        </div>

         <div class="form-group">
            @*@Html.LabelFor(model => model.HinhSP, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2">Hình sản phẩm</p>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.HinhSP, new { htmlAttributes = new { @class = "form-control" } })*@
                <img height="100" width="100" src="/@Model.HinhSP" />
                <input type="file" name="fileUpload" />
                @Html.ValidationMessageFor(model => model.HinhSP, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.MaMenu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaMenu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaMenu, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>